#!/usr/bin/env bash
# aw-openclaw-setup.sh — make the Agent Warden Tier-1 OpenClaw integration load
# DETERMINISTICALLY. One idempotent command that: builds the bridge, self-tests
# it, installs it on PATH behind a fixed-data-dir wrapper, (re)links + enables the
# plugin, restarts the Gateway, then ASSERTS via `plugins inspect` that the
# before_tool_call hook is actually registered. Exits 0 only if AW is governing.
#
# Why this exists: the flaky part of Tier-1 was never the broker — it was the
# manual install/enable/restart dance leaving the plugin un-hooked without anyone
# noticing (tool calls then run UNGOVERNED). This script turns "did it load? who
# knows" into a hard PASS/FAIL with actionable diagnostics.
#
# Target: Linux (the founder's throwaway OpenClaw VPS). Requires: go, node/npm,
# openclaw on PATH, and a completed `openclaw onboard`. jq is used if present.
#
# Usage:
#   scripts/aw-openclaw-setup.sh                 # build + install + wire + verify
#   AW_DATA_DIR=/root/aw-data scripts/aw-openclaw-setup.sh
#
# Licensed under the Apache License 2.0.
set -euo pipefail

# --- locate repo root (this script lives in <repo>/scripts/) ------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
REFERENCE="$REPO/reference"
ADAPTER="$REPO/adapters/openclaw"

AW_DATA_DIR="${AW_DATA_DIR:-/root/aw-data}"
BIN_DIR="${BIN_DIR:-/usr/local/bin}"
REAL_BIN="$BIN_DIR/aw-openclaw-bridge-bin"   # the actual Go binary
WRAPPER="$BIN_DIR/aw-openclaw-bridge"        # what the Gateway spawns (fixed -dir)

say()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m[OK]\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m[!]\033[0m %s\n' "$*"; }
die()  { printf '\n\033[31m[FAIL]\033[0m %s\n' "$*" >&2; exit 1; }

# --- 0. preconditions ---------------------------------------------------------
say "Checking prerequisites"
command -v go      >/dev/null || die "go not found. apt install golang-go (need 1.22+)."
command -v openclaw>/dev/null || die "openclaw not found. npm install -g openclaw@latest, then 'openclaw onboard'."
command -v jq      >/dev/null && HAVE_JQ=1 || { HAVE_JQ=0; warn "jq not found — falling back to grep for hook checks (apt install jq for strict checks)."; }
ok "go, openclaw present"

# --- 1. build the bridge ------------------------------------------------------
say "Building aw-openclaw-bridge"
( cd "$REFERENCE" && go build -o bin/aw-openclaw-bridge ./cmd/aw-openclaw-bridge )
ok "built $REFERENCE/bin/aw-openclaw-bridge"

# --- 2. self-test the binary in isolation (no OpenClaw) -----------------------
say "Self-testing the bridge (four-verdict mapping, no OpenClaw)"
"$REFERENCE/bin/aw-openclaw-bridge" -selftest || die "bridge self-test FAILED — do not wire a broken binary into OpenClaw."
ok "self-test PASS"

# --- 3. install on PATH behind a fixed-data-dir wrapper -----------------------
# The Gateway runs as a daemon and does NOT inherit your shell env, so we cannot
# rely on AW_BRIDGE_BIN / a shell-set -dir. We bake the data dir into a wrapper
# that the plugin finds by name on the daemon's PATH.
say "Installing bridge to $WRAPPER (data dir: $AW_DATA_DIR)"
mkdir -p "$AW_DATA_DIR"
install -m 0755 "$REFERENCE/bin/aw-openclaw-bridge" "$REAL_BIN"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by aw-openclaw-setup.sh. The Gateway spawns this; it pins the
# ledger/journal data dir because the daemon can't see your shell env.
exec "$REAL_BIN" -dir "$AW_DATA_DIR" "\$@"
EOF
chmod 0755 "$WRAPPER"
ok "installed $REAL_BIN + wrapper $WRAPPER -> -dir $AW_DATA_DIR"

# --- 4. (re)link + enable the plugin -----------------------------------------
say "Linking + enabling the OpenClaw plugin"
# install --link is idempotent-ish; ignore 'already installed' noise.
openclaw plugins install --link "$ADAPTER" 2>&1 | sed 's/^/  /' || true
openclaw plugins enable agent-warden        2>&1 | sed 's/^/  /' || true
ok "plugin linked + enabled"

# --- 5. restart the Gateway ---------------------------------------------------
say "Restarting the Gateway"
openclaw gateway restart 2>&1 | sed 's/^/  /' || die "gateway restart failed"
# Give the daemon a moment to load plugins.
sleep 3
ok "gateway restarted"

# --- 6. ASSERT the hook is registered ----------------------------------------
say "Verifying the before_tool_call hook is live"
INSPECT="$(openclaw plugins inspect agent-warden --runtime --json 2>/dev/null || true)"
[ -n "$INSPECT" ] || die "plugins inspect returned nothing — plugin not loaded. Check the Gateway log (see doctor script)."

if [ "$HAVE_JQ" = 1 ]; then
  ACTIVATED="$(printf '%s' "$INSPECT" | jq -r '.activated // .runtime.activated // empty' 2>/dev/null || true)"
  HOOK="$(printf '%s' "$INSPECT" | jq -r '
    [ (.typedHooks // .runtime.typedHooks // [])[]
      | (if type=="object" then (.name // .hook // .event) else . end) ]
    | map(select(.=="before_tool_call")) | length' 2>/dev/null || echo 0)"
  [ "$ACTIVATED" = "true" ] || warn "activated flag = '$ACTIVATED' (expected true)"
  [ "${HOOK:-0}" -ge 1 ] 2>/dev/null || die "before_tool_call NOT registered. AW is NOT governing tool calls. Re-run; if it persists, see the doctor script + Gateway log."
else
  printf '%s' "$INSPECT" | grep -q 'before_tool_call' \
    || die "before_tool_call NOT found in inspect output. AW is NOT governing. (Install jq for a strict check.)"
fi
ok "before_tool_call hook registered — Agent Warden is governing tool calls"

# --- 7. summary ---------------------------------------------------------------
cat <<EOF

$(printf '\033[32m========================================\033[0m')
$(printf '\033[1m AGENT WARDEN TIER-1: READY\033[0m')
$(printf '\033[32m========================================\033[0m')

  Bridge wrapper : $WRAPPER  (-dir $AW_DATA_DIR)
  Ledger         : $AW_DATA_DIR/.aw-openclaw/ledger.log

NEXT — drive a REAL tool call and confirm it was governed:
  1) Start the connected terminal UI (MUST be the gateway-backed one):
         openclaw tui
     ^ Use 'openclaw tui'. Do NOT use 'openclaw chat' / 'terminal' / 'tui --local'
       — those run EMBEDDED and BYPASS the gateway plugin (AW not in the loop).
       Confirm the status bar shows 'gateway connected'.
  2) Ask the agent to fetch a URL (expect an approval/escalate) or write a file.
  3) Verify the tamper-evident chain the bridge wrote:
         "$REFERENCE/bin/aw-openclaw-bridge" -version
         ( cd "$REFERENCE" && go run ./cmd/aw-verify -ledger "$AW_DATA_DIR/.aw-openclaw/ledger.log" )

  Health re-check any time:  scripts/aw-openclaw-doctor.sh
EOF
